sudo: false

language: node_js
node_js: 12

before_install:
  - npm install

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Test
      script:
        - npm test
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - npm run publish -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - npm run publish